backend:
  name: github
  repo: fupete/nasonero
  branch: main
  
media_folder: "src/assets/media"
public_folder: "/media"
publish_mode: editorial_workflow

collections:
  - label: "Notes in english"
    name: "notes-en"
    folder: "src/en/notes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # editor:
    #   preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Note in italiano"
    name: "notes-it"
    folder: "src/it/notes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # editor:
    #   preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }